config/routes.rb
Gardenr::Application.routes.draw do

  resources :users
  get "/users/:id/portfolio", to: "users#portfolio"
  resources :flowers do
    resources :comments, only: [:create, :edit, :destroy]
    resources :ratings, only: [:create, :edit, :destroy]
    collection do
      get 'next'
      get 'prev'
    end
    member do
      get 'skip_to'
    end
  end
  resources :session, only: [:new, :create, :destroy]
  root to: "pages#home"

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :flower

	validates :note, presence: true
end

app/models/flower.rb
class Flower < ActiveRecord::Base
	belongs_to :flower
	belongs_to :user
	has_many :comments
	has_many :ratings

	validates :url, presence: true
	validates :name, presence: true, length: { minimum: 3 }

	def rating
		i = 0
		self.ratings.each do |rating|
			i += 1 if rating.up_vote
		end
		if self.ratings.size > 0
			i.to_f / self.ratings.size
		else
			nil
		end
	end

	def score
		i = 0
		self.ratings.each do |rating|
			i += 1 if rating.up_vote
			i -= 1 if !rating.up_vote
		end
		i
	end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :flower

  validates_uniqueness_of :flower_id, scope: :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :flowers
	has_many :comments
	has_many :ratings

	has_secure_password # has before save shit to encrypt pw?
	valid_email = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :email, presence: true, format: { with: valid_email }, uniqueness: { case_sensitive: false }
	validates :password, :username, presence: true, length: { minimum: 5 }, on: :create # so it doesnt try and validate pw on update_attributes
	
	before_create { |user| user.email.downcase! }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  	def current_user
  		@current_user ||= User.find session[:user_id] unless session[:user_id].nil?
  	end

  	helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		if current_user
			@flower = Flower.find(params[:flower_id])
			@comment = @flower.comments.build comment_params
			@comment.user_id = current_user.id
			if @comment.save
				redirect_to @flower, notice: "Comment added"
			else
				redirect_to @flower
			end
		else
			redirect_to root_url
		end
	end

	def edit
	end

	def destroy
	end

	private

		def comment_params
			params.require(:comment).permit :note
		end
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
	def new
		if current_user
			@flower = Flower.new
			@categories = flower_categories
		else
			redirect_to root_url, notice: "Login to start adding to the gallery"
		end
	end

	def create
		@flower = Flower.new flower_params
		@flower.user_id = current_user.id
		if @flower.save
			#redirect_to @flower
			redirect_to root_url
		else
			render :new
		end
	end

	def index
		if current_user
			@flowers = Flower.all.reverse
			@range = current_user.gallery_range
			@active = current_user.active_flower
			@flower = Flower.find @active
			@user = @flower.user
			@comment = Comment.new if current_user
			@rating = Rating.new if current_user
			@categories = [{var: :note, placeholder: "Add a comment"}]
		else
			redirect_to root_url
		end
	end

	def next
		current_user.update_attributes(active_flower: current_user.active_flower - 1) if current_user.active_flower > 0
		current_user.update_attributes(gallery_range: current_user.gallery_range + 1) if page_switch
		redirect_to flowers_url
	end

	def prev
		current_user.update_attributes(gallery_range: current_user.gallery_range - 1) if page_switch
		current_user.update_attributes(active_flower: current_user.active_flower + 1)	if current_user.active_flower < Flower.all.size
		redirect_to flowers_url
	end

	def show
		@flower = Flower.find(params[:id])
		@user = User.find(@flower.user_id)
		@comment = Comment.new if current_user
		@rating = Rating.new if current_user
		@categories = [{var: :note, placeholder: "Add a comment"}]
	end

	def skip_to
		@flower = Flower.find(params[:id])
		current_user.update_attributes(active_flower: @flower.id)
		redirect_to flowers_url
	end

	def edit
	end

	def destroy
	end

	private

		def flower_params
			params.require(:flower).permit :url, :name, :description
		end

		def flower_categories
			url = { var: :url, placeholder: "Image URL" }
			name = { var: :name, placeholder: "Name" }
			description = { var: :description, placeholder: "Description" }
			[url, name, description]
		end

		def page_switch
			(Flower.all.size - current_user.active_flower) % 10 == 0
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		if current_user
			redirect_to current_user
		else
			render action: "landing_page"
		end
	end

	def landing_page
	end

	def about
	end

	def contact
	end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
	def create
		if current_user
			@flower = Flower.find(params[:flower_id])
			@user = current_user
			@rating = Rating.where(flower: @flower, user: @user).first
			if @rating.nil? #user hasnt rated yet
				@rating = @flower.ratings.build rating_params
				@rating.user = @user
				@rating.save
			else
				Rating.destroy @rating
			end
			redirect_to @flower
		else
			redirect_to root_url
		end
	end

	private

		def rating_params
			params.require(:rating).permit :up_vote
		end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	def new
	end

	def create
		@user = User.find_by_email params[:email]
		if @user && @user.authenticate(params[:password]) # login
			session[:user_id] = @user.id
			@user.gallery_range = 0
			@user.active_flower = Flower.last.id
			@user.save
			redirect_to root_url
		else #wrong login details
			flash.now[:alert] = "Wrong login details"
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
		@categories = categories_array
	end

	def create
		@user = User.new user_params #wtf how does rails know password and password_confirmation must match, and how
																 # does bcrypt know to encrypt the pw before saving to the db as password_digest?
		@categories = categories_array
		if @user.save
			redirect_to @user, notice: "Thanks for signing up! Feel free to start adding your creations, or check out the gallery"
			session[:user_id] = @user.id
			@user.update_attributes gallery_range: 0, active_flower: Flower.last.id
			current_user = @user
		else
			render :new
		end
	end

	def edit
		@user = current_user
	end

	def show
		@user = User.find(params[:id])
		@flowers = @user.flowers.reverse
	end

	def portfolio
		@user = User.find(params[:id])
		@flowers = @user.flowers.reverse
	end

	private

		def user_params
			params.require(:user).permit :email, :username, :password, :password_confirmation
		end

		def categories_array
			name = { var: :username, placeholder: "User name" }
			email = { var: :email, placeholder: "Email" }
			pw = { var: :password, placeholder: "Password" }
			pw_conf = { var: :password_confirmation, placeholder: "Retype password" }
			[name, email, pw, pw_conf]
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/flowers/_display_flower.html.erb
<div id="flower_container">
	<h2><%= @flower.name %></h2>
	<img src=<%= @flower.url %> alt="Flower">
	<p class="flower_description"><%= @flower.description %></p>
	<p class="author">
		Submitted by <%= link_to @user.username, @user %> on <%= @flower.created_at.strftime("%B %d, %Y") %>
	</p>
</div>

<div class="rate">
<%= @flower.rating %>
<%= @flower.score %>
<% @flower.ratings.each do |rating| %>
<%= rating.up_vote %>
<% end %>
<% if current_user %>
		<%= render "ratings_form" %>
<% end %>
</div>

<div class="comments">
	<h3>Comments:</h3>
	<ul>
	<% @flower.comments.each do |comment| %>
		<li><%= "#{comment.note} - " %><%= link_to User.find(comment.user_id).username, User.find(comment.user_id) %>
		<%= " on #{comment.created_at.strftime("%B %d, %Y")}" %></li>
	<% end %>
	</ul>
<%= render "layouts/model_form", object: [@flower, @comment], categories: @categories if current_user %>
</div>

app/views/flowers/_ratings_form.html.erb
<%= form_for [@flower, @rating] do |f| %>
	<%= f.hidden_field :up_vote, value: true %>
	<%= f.submit value: "Upvote", id: "upvote" %>
<% end %>

<%= form_for [@flower, @rating] do |f| %>
	<%= f.hidden_field :up_vote, value: false %>
	<%= f.submit value: "Downvote", id: "downvote" %>
<% end %>

app/views/flowers/index.html.erb
<div class="gallery_top">
	<ul>
		<% if @active < @flowers.size %>
			<li><%= link_to prev_flowers_url, id:"prev" do %><button class="btn-large prev">-</button><% end %>
		<% else %>
			<button class="btn-large prev">-</button>
		<% end %>
	<% @flowers[(@range * 10)..((@range + 1) * 10 - 1)].each do |flower| %>
		<li><%= link_to skip_to_flower_url(flower) do %>
			<img src=<%= flower.url %> alt="Flower" height="100" width="100" id=<%= "active" if flower.id == @active %>><% end %>
		</li>
	<% end %>
	<% if @active > 1 %>
		<li><%= link_to next_flowers_url, id:"next" do %><button class="btn-large next">+</button><% end %>
	<% else %>
		<button class="btn-large next">+</button>
	<% end %>
	</ul>
</div>

<div class="gallery_display">
	<%= render "display_flower" %>
</div>

app/views/flowers/new.html.erb
<div class="add_new_flower">
	<%= render "layouts/model_form", object: @flower, categories: @categories %>
</div>

app/views/flowers/show.html.erb
<%= render "display_flower" %>

app/views/layouts/_model_form.html.erb
<!-- Create a form for any model which requries text fields only
		 object is model, categories is array of hashes with variable and text placeholders -->
<%= form_for object do |f| %>
	<% categories.each do |cat| %>
		<% if cat[:var].to_s.include? "password" %>
			<%= f.password_field cat[:var], placeholder: cat[:placeholder] %>
		<% else %>
			<%= f.text_field cat[:var], placeholder: cat[:placeholder] %>
		<% end %>
	<% end %>
	<% if object.respond_to? :errors %>
		<% if object.errors.any? %>
			<div id="error">
				<%= object.errors.full_messages.first %>
			</div>
		<% end %>
	<% end %>
	<%= f.submit value: "+", class: "btn-large" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Croissant+One|Berkshire+Swash|Cherry+Swash' rel='stylesheet' type='text/css'>
</head>
<body>
	<header class = "navbar navbar-fixed-top">
		<nav class ="navbar inner">
			<ul class="nav">
				<li><%= link_to "Home", root_url %>
				<li><%= link_to "Gallery", flowers_url %>
				<% if current_user %>
					<li><%= link_to "Portfolio", "/users/#{current_user.id}/portfolio" %></li>
					<li><%= link_to "Logout", session_url("doesntmatter"), method: :delete %></li>
				<% else %>
					<li><%= link_to "Login", new_session_path %></li>
					<li><%= link_to "Signup", new_user_path %></li>
				<% end %>
			</ul>
		</nav>
	</header>

<%= yield %>

</body>
</html>

app/views/pages/landing_page.html.erb
<div class="landing_page container">
	<div id="logo">GardenR</div>
	<p id="pitch">A simple way for plant lovers and nature photographers to share their work
		and get feedback from the community. Sign up is quick, easy, and free.</p>
</div>

app/views/session/new.html.erb
<div class="signin">
	<%= form_tag session_index_url do %>
		<%= text_field_tag :email, nil, placeholder: "Email" %>
		<%= password_field_tag :password, nil, placeholder: "Password" %>
		<% if flash[:alert] %>
			<div id="error">
				<%= flash[:alert] %>
			</div>
		<% end %>
		<%= submit_tag nil, value: "+", class: "btn-large" %>
	<% end %>
</div>

app/views/users/_recent_pictures.html.erb
<% if @flowers %>
	<div class="recent_pictures">
	<% @flowers[0..3].each_with_index do |flower, i| %>
		<%= link_to flower do %>
			<img src=<%= flower.url %> alt="Flower" height="200" width="200" id=<%= "image_#{i}" %>>
		<% end %>
	<% end %>
	</div>
<% end %>

app/views/users/new.html.erb
<div class="signup">
	<%= render 'layouts/model_form', object: @user, categories: @categories %>
</div>

app/views/users/portfolio.html.erb
<div class="portfolio_container">
	<% @flowers.each do |flower| %>
		<%= link_to flower do %>
				<img src=<%= flower.url %> alt="Flower" height="200" width="200">
			<% end %>
	<% end %>
</div>

app/views/users/show.html.erb
<article class="recent_pictures_container">

<% if @user == current_user %>
	<h3>Recently Added Pictures</h3>
	<%= render "recent_pictures" %>
</article>
	<button id="add_picture_link">
		<%= link_to new_flower_path do %>+<% end %>
	</button>

<% else %>

<h3><%= @user.username %>'s Recently Added Pictures</h3>
	<%= render "recent_pictures" %>
	</article>
	<aside class="user_contact_and_portfolio">
		<h4>Contact:</h4>
		<p>You can reach <%= @user.username %> at <%= @user.email %></p>
		<%= link_to "Check out their portfolio", "/users/#{@user.id}/portfolio" %>
	</aside>

<% end %>